@startuml

!define ENTITY class
!define ENDENTITY end class

ENTITY VaccineTech{
    name [pk]
    description
}
ENTITY VaccineType {
    Code [pk]
    ShortDescription
}

ENTITY Vaccine {
    Id [pk]
    Name
    Brand
}

ENTITY SNSUser {
    Id [pk]
    Name
    BirthDate
    Sex
    PostalAddress
    PhoneNumber
    EmailAddress
    CitizenCardNumber
    SNSUserNumber
}

ENTITY VaccinationCenter {
    Id [pk]
    Name
    Location
    ContactInformation
    Capacity
}

ENTITY Receptionist {
    Name
}

ENTITY Nurse {
    Name
    VaccinationCenterId [fk]
}

ENTITY HealthCenter {
     Id [pk]
     Name
     Location
}

ENTITY VaccineAppointment {
    Id
       DateTime
       Status
    SNSUserId [fk]
    VaccinationCenterId [fk]
    CheckInId [fk]
}


ENTITY VaccinationCall {
Status
NurseId [fk]
LocalId [fk]
RegisterVaccinationId [fk]
}


ENTITY AdverseSymptomsRegister {
    Id [pk]
    Symptoms
    RegisterVaccinationId [fk]
}

ENTITY Lot {
    Id [pk]
    Quantity
    ManufacturingDate
    ExpiryDate
    VaccineId [fk]
}

ENTITY Local {
    Id [pk]
    Name
}

ENTITY CheckIn {
    Status
    ReceptionistId [fk]
    LocalId [fk]
    VaccinationCallId [fk]
}

ENTITY WaitingRoom {
    Capacity
    LocalId [fk]
}

ENTITY VacinationRoom {
    Capacity
    LocalId [fk]
}

ENTITY RecoveryRoom {
    Capacity
    LocalId [fk]
}

ENTITY RegisterVacination {
    Id [pk]
    VaccinationAppointmentId [fk]
    AdverseSymptomsRegisterId [fk]
    VaccineId [fk]
}



VaccinationCenter "*" -- "*" Nurse
VaccinationCenter "*" -- "*" Receptionist
VaccineAppointment "0..1" -- "0..*" CheckIn
VaccineAppointment "*" -- "1" SNSUser
VaccineAppointment "*" -- "1" VaccinationCenter
VaccinationCall "*" -- "1" Nurse
VaccinationCall "1" -- "0..*" Local
VaccinationCall "1" -- "1" RegisterVacination
RegisterVacination "1" -- "1" AdverseSymptomsRegister
RegisterVacination "1" -- "1" Lot
CheckIn "0..1" -- "1" Receptionist
CheckIn "0" -- "1" Local
CheckIn "1" -- "0..1" VaccinationCall
Lot "*" -- "1" Vaccine
Vaccine "*" -- "1" VaccineType
Local "0..1" -- "0..1" WaitingRoom
Local "0..1" -- "0..1" VacinationRoom
Local "0..1" -- "0..1" RecoveryRoom
VaccineType "*" -- "1" VaccineTech
HealthCenter "0..1" -- "0..1" VaccinationCenter



@enduml
